# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_auto_20170323_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.DecimalField(decimal_places=10, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='articles',
            field=models.ManyToManyField(through='analytics.KeywordAnalysis', to='content.Article'),
        ),
    ]
