# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
