# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170323_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
